name: Ejecutar test de repositorio
run-name: ${{ github.actor }} esta ejecutando test en el repositorio ðŸš€

on: 
  push:
    # paths:
    #   - 'src/**' 

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_HOST: mysql
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sonder
          MYSQL_USER: myuser
          MYSQL_PASSWORD: secret
        ports:
          - "3306:3306"
    steps:
      - name: Copia del repositorio
        uses: actions/checkout@v4 
        
      - name: Instalando dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esperar a que MySQL estÃ© disponible
        run: sleep 30s
        

      - name: Ejecutando tests de repositorio
        run: |
          cd src
          invoke test
