name: Run test 
run-name: ${{ github.actor }} is running tests ðŸš€

on: 
  push:
    paths:
      - 'src/**' 

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sonder
          MYSQL_USER: myuser
          MYSQL_PASSWORD: secret
        ports:
          - "3306:3306"
      sonder:
        image: pvalenz23/sonder:latest
        ports:
          - "8000:8000"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Espera a que la base de datos esta iniciada
        run: sleep 10  
      
      - name: script de inicializaciÃ³n
        run: |
          mysql -h localhost -u myuser -psecret < src/BBDD/init2.sql
      

      - name: Sonder tests
        run: |
          cd sonder/src
          invoke test
